### PR TITLE
cvmfs-with-clang

### PR DESCRIPTION
**Pull request by claudiok**
I put in some work on setting up bootstrapping a clang+libc++11 (based on cweaver's instructions given in the relevant ticket) and then installing the cvmfs tools (calling it py2-v3 for now).

Not all tools are compiling yet and this is basically untested (icetray starts compiling just fine so far, but I haven't tested things much yet... )

A working installation can be found here: eval `/data/user/ckopper/tools/py2-v3/setup.sh`

### CODE REVIEW

**Comment by dsschult** [comment]
My one question is why the compiler gets put into the same space as the rest of our software.  It might be useful to separate them, so we can use the same compiler for multiple software versions.

**Comment by claudiok** [comment]
some of the tools might depend on the compiler - we can disentangle this but my feeling was that keeping things together would make them more manageable

**Comment by claudiok** [comment]
I changed the installation directory name to `py2-v3_early_access` to make it clear that this isn't official yet

**Comment by dsschult** [comment]
I don't see the change added to the pull request.  Maybe you forgot that part?

**Comment by claudiok** [comment]
somehow my last patch did not show up in here. I will close this and create a new pull request

**Pull request closed without merging**
